apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dns-app
  template:
    metadata:
      labels:
        app: dns-app
    spec:
      containers:
      - name: authoritative-server
        image: docker.io/elien2016/authoritative-server
        ports:
        - containerPort: 53533
          protocol: UDP
      - name: fibonacci-server
        image: docker.io/elien2016/fibonacci-server
        ports:
        - containerPort: 9090
      - name: user-server
        image: docker.io/elien2016/user-server
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dns-service
spec:
  type: NodePort
  selector:
    app: dns-app
  ports:
    - name: authoritative-server
      protocol: UDP
      port: 53533
      targetPort: 53533
      nodePort: 30001
    - name: fibonacci-server
      port: 9090
      targetPort: 9090
      nodePort: 30002
    - name: user-server
      port: 8080
      targetPort: 8080
      nodePort: 30003
